FROM openwrt/sdk:x86_64-v24.10.6

WORKDIR /builder

# Kept in a separate layer so that CI can reuse the downloaded feeds from cache
RUN ./scripts/feeds update -a && \
    ./scripts/feeds install luci-base && \
    mkdir -p /builder/package/feeds/utilities/ /builder/package/feeds/luci/

ARG OKOP_VERSION

COPY ./okop /builder/package/feeds/utilities/okop
COPY ./luci-app-okop /builder/package/feeds/luci/luci-app-okop

RUN export OKOP_VERSION="v${OKOP_VERSION}" && \
    make defconfig && \
    make package/okop/compile V=s -j4 && \
    make package/luci-app-okop/compile V=s -j4
