#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034
# Dev environment only: marks the end of the boot sequence for dev/okop-dev.

START=98

start() {
    if [ -f /tmp/devenv.start-okop ]; then
        rm -f /tmp/devenv.start-okop
        /etc/init.d/okop start
    fi

    touch /tmp/devenv.ready
}
